import sendEmail from "../services/sendEmail.js";

const TEST_MODE = process.env.EMAIL_TEST_MODE === "true";
const TEST_EMAIL = "hazwanihanafi@gmail.com";

/* =========================================================
   ⏰ DELAY ALERT → STUDENT (CC SUPERVISOR ONLY)
========================================================= */
   export async function sendDelayAlert({
  studentName,
  studentEmail,
  supervisorEmail,
  studentStatus,
  delays,
}) {

  console.log("===== INSIDE sendDelayAlert =====");
  console.log({
    studentName,
    studentStatus,
    studentEmail,
    supervisorEmail,
  });

// Only send to ACTIVE or STUDY SUSPENSION students
const status = (studentStatus || "").trim().toUpperCase();

const allowedStatuses = ["ACTIVE", "STUDY SUSPENSION"];

if (!allowedStatuses.includes(status)) {
  console.log(
    `⏭️ Skipping email for ${studentName} (Status: ${studentStatus})`
  );
  return;
}

  // ✅ Basic validation
  if (!studentEmail || !studentEmail.includes("@")) {
    throw new Error("Invalid student email");
  }

  // Supervisor email is optional
if (supervisorEmail && !supervisorEmail.includes("@")) {
  throw new Error("Invalid supervisor email");
}

  if (!Array.isArray(delays)) {
    throw new Error("Delays must be an array");
  }

  const validDelays = delays.filter(
    d => d && d.activity && typeof d.remaining_days === "number"
  );

  if (validDelays.length === 0) {
    throw new Error("No valid delayed milestones");
  }

  const delayList = validDelays
    .map(d => `• ${d.activity} (Delayed ${Math.abs(d.remaining_days)} days)`)
    .join("\n");

  const emailText = (
`Dear ${studentName},

This is an automated notification from the Postgraduate Progress Based Monitoring System (PPBMS), a progress monitoring system developed by the Pusat Kanser Tun Abdullah Ahmad Badawi (PKTAAB), Universiti Sains Malaysia, to facilitate the monitoring of postgraduate students' research progress and milestones.

PPBMS has been introduced to postgraduate students through a series of briefing and training workshops. Students are expected to keep their research progress records accurate and up to date throughout their candidature.

Based on the current records in PPBMS, the following research milestone(s) are overdue:

${delayList}

Action Required

• Please log in to PPBMS using your USM email address and password.

PPBMS Login:
https://ppbms.my/

If you have not previously activated your PPBMS account, please click "Set Password" on the login page to create your password before logging in.
  
• If you have already completed any of the milestones listed above, please mark the milestone as "Completed" in PPBMS.
• Please upload the link of the relevant supporting documents for each completed milestone. These documents serve as official evidence for postgraduate progress monitoring, programme quality assurance, and institutional audit purposes.
• If you believe the information displayed is inaccurate or require assistance, please consult your supervisor or contact the PPBMS Administrator.

PPBMS Administrator
Assoc. Prof. Dr. Hazwani Ahmad Yusof @ Hanafi
Deputy Director (Academic & International)
Pusat Kanser Tun Abdullah Ahmad Badawi (PKTAAB)
Universiti Sains Malaysia
Email: hazwanihanafi@usm.my

This notification has been copied to your supervisor for information and progress monitoring.

Thank you for your prompt attention and cooperation in ensuring that your postgraduate research records in PPBMS remain accurate, complete, and up to date.

Kind regards,

PPBMS Notification System
Postgraduate Progress Based Monitoring System (PPBMS)
Pusat Kanser Tun Abdullah Ahmad Badawi (PKTAAB)
Universiti Sains Malaysia

This is an automated email generated by PPBMS. Please do not reply directly to this email.`
).trim();

      const milestoneRows = validDelays.map(d => `
<tr>
  <td style="padding:12px;border:1px solid #ddd;">
    ${d.activity}
  </td>

  <td align="center"
      style="padding:12px;border:1px solid #ddd;">
      <span style="
        background:#d32f2f;
        color:#fff;
        padding:4px 10px;
        border-radius:12px;
        font-size:12px;
        font-weight:bold;">
        DELAYED
      </span>
      <br>
      <span style="font-size:13px;color:#555;">
        ${Math.abs(d.remaining_days)} day(s)
      </span>
  </td>
</tr>
`).join("");

const emailHtml = `
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
</head>

<body style="
margin:0;
background:#f3f5f7;
font-family:Arial,Helvetica,sans-serif;
">

<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td align="center">

<table width="720" cellpadding="0" cellspacing="0"
style="
background:white;
margin:30px auto;
border-radius:10px;
overflow:hidden;
box-shadow:0 2px 10px rgba(0,0,0,.08);
">

<tr>
<td style="
background:#53257f;
padding:30px;
text-align:center;
color:white;
">

<h1 style="margin:0;">
PPBMS
</h1>

<p style="margin:8px 0;font-size:18px;">
Postgraduate Progress Based Monitoring System
</p>

<p style="margin:0;color:#f7d774;">
Pusat Kanser Tun Abdullah Ahmad Badawi (PKTAAB)<br>
Universiti Sains Malaysia
</p>

</td>
</tr>

<tr>
<td style="padding:35px;">

<h2 style="color:#53257f;margin-top:0;">
Milestone Delay Alert
</h2>

<p>
Dear <strong>${studentName}</strong>,
</p>

<p>
This is an automated notification from the
<strong>Postgraduate Progress Based Monitoring System (PPBMS)</strong>,
developed by
<strong>Pusat Kanser Tun Abdullah Ahmad Badawi (PKTAAB),
Universiti Sains Malaysia</strong>,
to facilitate the monitoring of postgraduate students'
research progress and milestones.
</p>

<p>
PPBMS has been introduced through postgraduate briefing and
training workshops. Students are expected to maintain
accurate and up-to-date research records throughout
their candidature.
</p>

<h3 style="color:#53257f;">
Overdue Milestones
</h3>

<table width="100%"
style="
border-collapse:collapse;
margin-top:15px;
margin-bottom:30px;
">

<tr style="background:#f4f4f4;">
<th style="padding:12px;border:1px solid #ddd;text-align:left;">
Milestone
</th>

<th style="padding:12px;border:1px solid #ddd;">
Status
</th>

</tr>

${milestoneRows}

</table>

<div style="text-align:center;margin:40px 0;">

<a href="https://ppbms.my/"
style="
background:#53257f;
color:white;
text-decoration:none;
padding:16px 36px;
border-radius:8px;
font-size:18px;
font-weight:bold;
display:inline-block;
">

Login to PPBMS

</a>

</div>

<h3 style="color:#53257f;">
Action Required
</h3>

<ul style="line-height:1.8;">

<li>
Log in to PPBMS using your USM email address and password.
</li>

<li>
If this is your first login, click
<strong>Set Password</strong>
to activate your account.
</li>

<li>
Update any completed milestones in PPBMS.
</li>

<li>
Upload the supporting document link for each completed milestone.
</li>

<li>
These documents serve as official evidence for postgraduate
progress monitoring, programme quality assurance (QA),
and institutional audit purposes.
</li>

<li>
If you believe the information displayed is inaccurate,
please consult your supervisor or contact the PPBMS Administrator.
</li>

</ul>

<hr style="margin:35px 0;">

<h3 style="color:#53257f;">
Why am I receiving this email?
</h3>

<p>
This notification has been copied to your supervisor
for information and progress monitoring.
</p>

<p>
Timely updates in PPBMS help ensure that your
postgraduate research records remain accurate,
complete and up to date.
</p>

<hr style="margin:35px 0;">

<h3 style="color:#53257f;">
PPBMS Administrator
</h3>

<p style="line-height:1.7;">

<strong>
Assoc. Prof. Dr. Hazwani Ahmad Yusof @ Hanafi
</strong><br>

Deputy Director (Academic & International)<br>

Pusat Kanser Tun Abdullah Ahmad Badawi (PKTAAB)<br>

Universiti Sains Malaysia<br><br>

📧
<a href="mailto:hazwanihanafi@usm.my">
hazwanihanafi@usm.my
</a>

</p>

<hr>

<p style="
font-size:12px;
color:#777;
text-align:center;
">

This is an automated email generated by the
<strong>Postgraduate Progress Based Monitoring System (PPBMS)</strong>.

<br><br>

Please do not reply directly to this email.

</p>

</td>
</tr>

</table>

</td>
</tr>
</table>

</body>
</html>
`;
  // 🔒 TEST MODE GUARD
  const toEmail = TEST_MODE ? TEST_EMAIL : studentEmail;
  const ccEmail = TEST_MODE ? undefined : supervisorEmail;

  console.log("📧 Sending delay alert:", {
    to: toEmail,
    cc: ccEmail,
    testMode: TEST_MODE,
    milestones: validDelays.map(d => d.activity),
  });

  await sendEmail({
  to: toEmail,
  cc: ccEmail,
  subject: TEST_MODE
    ? `[PPBMS TEST] Milestone Delay Alert – ${studentName}`
    : `[PPBMS] Milestone Delay Alert – ${studentName}`,
  text: emailText,      // Fallback for clients that don't support HTML
  html: emailHtml,      // HTML version
});
      
}
/* =========================================================
   📊 CQI ALERT → SUPERVISOR (STUDENT NOT COPIED)
========================================================= */
export async function sendCQIAlert({
  supervisorEmail,
  studentName,
  matric,
  studentStatus,
  assessmentType,
  cqiIssues,
}) {

   // Only send CQI notifications for ACTIVE or STUDY SUSPENSION students
const status = (studentStatus || "").trim().toUpperCase();

const allowedStatuses = ["ACTIVE", "STUDY SUSPENSION"];

if (!allowedStatuses.includes(status)) {
  console.log(
    `⏭️ Skipping CQI alert for ${studentName} (Status: ${studentStatus})`
  );
  return;
}
  // 🔍 DEBUG LOGS (CRITICAL — MUST BE BEFORE VALIDATION)
  console.log("📧 CQI supervisorEmail =", supervisorEmail);
  console.log("📧 CQI payload =", {
    supervisorEmail,
    studentName,
    matric,
    assessmentType,
    cqiIssues,
  });

  if (!supervisorEmail || !supervisorEmail.includes("@")) {
    throw new Error("Invalid supervisor email");
  }

  if (!Array.isArray(cqiIssues) || cqiIssues.length === 0) {
    throw new Error("Invalid CQI issues");
  }

  const issuesText = cqiIssues
    .map(i => `• ${i.plo}: ${i.reason}`)
    .join("\n");

   const issuesRows = cqiIssues.map(i => `
<tr>
<td style="padding:12px;border:1px solid #ddd;">
${i.plo}
</td>

<td style="padding:12px;border:1px solid #ddd;">
${i.reason}
</td>
</tr>
`).join("");

  const emailText = (
    `Dear Supervisor,

Continuous Quality Improvement (CQI) has been automatically detected.

Student    : ${studentName}
Matric     : ${matric}
Assessment : ${assessmentType}

Affected PLO(s):
${issuesText}

(Student is NOT copied.)

Please log in to PPBMS and record intervention within 30 days.

— PPBMS System`
  ).trim();

   const emailHtml = `
<!DOCTYPE html>
<html>

<body style="
margin:0;
background:#f3f5f7;
font-family:Arial,sans-serif;
">

<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td align="center">

<table width="720"
style="
background:white;
margin:30px auto;
border-radius:10px;
overflow:hidden;
">

<tr>
<td style="
background:#53257f;
padding:30px;
text-align:center;
color:white;
">

<h1 style="margin:0;">
PPBMS
</h1>

<p style="margin:8px 0;">
Postgraduate Progress Based Monitoring System
</p>

<p style="margin:0;color:#F7D774;">
Pusat Kanser Tun Abdullah Ahmad Badawi (PKTAAB)<br>
Universiti Sains Malaysia
</p>

</td>
</tr>

<tr>
<td style="padding:35px;">

<div style="margin-bottom:20px;">

<span style="
background:#1565C0;
color:white;
padding:6px 16px;
border-radius:20px;
font-size:13px;
font-weight:bold;
">

QUALITY ALERT

</span>

<h2 style="
margin-top:18px;
color:#53257f;
">

Continuous Quality Improvement (CQI)

</h2>

</div>
<p>
Dear Supervisor,
</p>

<p>
A <strong>Continuous Quality Improvement (CQI)</strong> issue has been identified.
Please review the student's assessment results and record the
appropriate intervention in PPBMS.
</p>

<p>
This notification was automatically generated because one or more
<strong>Programme Learning Outcomes (PLOs)</strong> did not meet the
predefined performance threshold. In accordance with the faculty's
Continuous Quality Improvement (CQI) process, supervisory review and
documentation of the intervention are required.
</p>

<h3 style="color:#53257f;">
Student Information
</h3>

<table width="100%"
style="border-collapse:collapse;">

<tr>
<td style="padding:10px;border:1px solid #ddd;"><b>Student</b></td>
<td style="padding:10px;border:1px solid #ddd;">
${studentName}
</td>
</tr>

<tr>
<td style="padding:10px;border:1px solid #ddd;"><b>Matric</b></td>
<td style="padding:10px;border:1px solid #ddd;">
${matric}
</td>
</tr>

<tr>
<td style="padding:10px;border:1px solid #ddd;"><b>Assessment</b></td>
<td style="padding:10px;border:1px solid #ddd;">
${assessmentType}
</td>
</tr>

</table>

<h3 style="color:#53257f;">
Affected PLO(s)
</h3>

<table width="100%"
style="border-collapse:collapse;">

<tr style="background:#53257f;color:white;">

<th style="padding:12px;border:1px solid #ddd;">
Programme Learning Outcome (PLO)
</th>

<th style="padding:12px;border:1px solid #ddd;">
Reason
</th>

</tr>

${issuesRows}

</table>

<div style="
background:#E8F4FD;
border-left:5px solid #1976D2;
padding:18px;
margin:30px 0;
border-radius:6px;
">

<strong style="color:#1565C0;">
Important Information
</strong>

<p style="margin:10px 0 0 0;line-height:1.6;">

This notification has been sent only to the registered supervisor
as part of the <strong>Continuous Quality Improvement (CQI)</strong>
process.

The student has <strong>not</strong> been copied in this email.

Please review the assessment outcome and record the appropriate
CQI intervention in PPBMS within <strong>30 days</strong>.

</p>

</div>

<div style="text-align:center;margin:35px;">

<a href="https://ppbms.my/"
style="
background:#53257f;
color:white;
padding:16px 40px;
text-decoration:none;
border-radius:8px;
font-weight:bold;
font-size:16px;
display:inline-block;
box-shadow:0 2px 6px rgba(0,0,0,.15);
">
Review & Record CQI Intervention
</a>

</div>

<h3 style="color:#53257f;">
Action Required
</h3>

<ul style="line-height:1.8; padding-left:20px;">

<li>
Review the student's assessment results and identify the underlying cause(s) of the affected Programme Learning Outcome(s) (PLOs).
</li>

<li>
Record the appropriate <strong>Continuous Quality Improvement (CQI)</strong> intervention and follow-up action in PPBMS.
</li>

<li>
Complete and document the intervention within <strong>30 days</strong> of receiving this notification.
</li>

<li>
This notification has been sent <strong>only to the registered supervisor</strong>. The student has <strong>not</strong> been copied in this email.
</li>

</ul>

<hr style="
margin:40px 0;
border:none;
border-top:1px solid #ddd;
">

<div style="
background:#F7F7F7;
padding:20px;
border-radius:8px;
margin:25px 0;
">

<h3 style="
margin:0 0 15px 0;
color:#53257f;
">
PPBMS Administrator
</h3>

<p style="
margin:0;
line-height:1.8;
color:#333;
">

<strong>
Assoc. Prof. Dr. Hazwani Ahmad Yusof @ Hanafi
</strong><br>

Deputy Director (Academic & International)<br>

Pusat Kanser Tun Abdullah Ahmad Badawi (PKTAAB)<br>

Universiti Sains Malaysia

</p>

<p style="
margin:15px 0 0 0;
">

📧
<a href="mailto:hazwanihanafi@usm.my"
style="
color:#53257f;
text-decoration:none;
font-weight:bold;
">
hazwanihanafi@usm.my
</a>

</p>

</div>

<p style="
font-size:12px;
color:#777;
text-align:center;
line-height:1.7;
margin-top:30px;
">

This notification was automatically generated by the
<strong>Postgraduate Progress Based Monitoring System (PPBMS)</strong>,
developed by
<strong>Pusat Kanser Tun Abdullah Ahmad Badawi (PKTAAB),
Universiti Sains Malaysia</strong>,
to support postgraduate progress monitoring, Continuous Quality Improvement (CQI),
and institutional quality assurance.

<br><br>

Please do not reply directly to this email.
For enquiries or technical assistance, please contact the PPBMS Administrator.

</p>

</td>
</tr>

</table>

</td>
</tr>

</table>

</body>
</html>
`;

  const toEmail = TEST_MODE ? TEST_EMAIL : supervisorEmail;

await sendEmail({
  to: toEmail,
  subject: TEST_MODE
    ? `[PPBMS TEST] CQI Detected – ${studentName}`
    : `[PPBMS] CQI Detected – ${studentName} (${assessmentType})`,
  text: emailText,
  html: emailHtml,
});
   
}
/* =========================================================
   🔔 CQI REMINDER → SUPERVISOR
========================================================= */
export async function sendCQIReminder({
  supervisorEmail,
  studentName,
  matric,
  studentStatus,
  assessmentType,
  daysPending,
}) {
  // Only send CQI reminders for ACTIVE or STUDY SUSPENSION students
  const status = (studentStatus || "").trim().toUpperCase();

  const allowedStatuses = ["ACTIVE", "STUDY SUSPENSION"];

  if (!allowedStatuses.includes(status)) {
    console.log(
      `⏭️ Skipping CQI reminder for ${studentName} (Status: ${studentStatus})`
    );
    return;
  }

  if (!supervisorEmail || !supervisorEmail.includes("@")) {
    throw new Error("Invalid supervisor email");
  }

  const emailText = (
`Dear Supervisor,

This is an automated reminder from the Postgraduate Progress Based Monitoring System (PPBMS).

A Continuous Quality Improvement (CQI) case remains pending.

Student    : ${studentName}
Matric     : ${matric}
Assessment : ${assessmentType}
Days Pending : ${daysPending} day(s)

Action Required

• Review the outstanding CQI case.
• Record the appropriate CQI intervention and follow-up action in PPBMS.
• Complete and document the intervention as soon as possible.
• The student has NOT been copied in this email.

PPBMS Administrator
Assoc. Prof. Dr. Hazwani Ahmad Yusof @ Hanafi
Deputy Director (Academic & International)
Pusat Kanser Tun Abdullah Ahmad Badawi (PKTAAB)
Universiti Sains Malaysia
Email: hazwanihanafi@usm.my

This is an automated email generated by PPBMS.
Please do not reply directly to this email.
`
  ).trim();

  const emailHtml = `
<!DOCTYPE html>
<html>

<body style="
margin:0;
background:#f3f5f7;
font-family:Arial,Helvetica,sans-serif;
">

<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td align="center">

<table width="720"
style="
background:white;
margin:30px auto;
border-radius:10px;
overflow:hidden;
box-shadow:0 2px 10px rgba(0,0,0,.08);
">

<tr>

<td style="
background:#53257f;
padding:30px;
text-align:center;
color:white;
">

<h1 style="margin:0;">
PPBMS
</h1>

<p style="margin:8px 0;font-size:18px;">
Postgraduate Progress Based Monitoring System
</p>

<p style="margin:0;color:#F7D774;">
Pusat Kanser Tun Abdullah Ahmad Badawi (PKTAAB)<br>
Universiti Sains Malaysia
</p>

</td>

</tr>

<tr>

<td style="padding:35px;">

<div style="margin-bottom:20px;">

<span style="
background:#F57C00;
color:white;
padding:6px 16px;
border-radius:20px;
font-size:13px;
font-weight:bold;
">

CQI REMINDER

</span>

<h2 style="
margin-top:18px;
color:#53257f;
">

Pending Continuous Quality Improvement (CQI)

</h2>

</div>

<p>

Dear Supervisor,

</p>

<p>

This is a reminder that a
<strong>Continuous Quality Improvement (CQI)</strong>
case remains pending.

Please review the student's assessment and complete the
required CQI intervention in PPBMS.

</p>

<h3 style="color:#53257f;">

Student Information

</h3>

<table width="100%" style="border-collapse:collapse;">

<tr>
<td style="padding:10px;border:1px solid #ddd;"><b>Student</b></td>
<td style="padding:10px;border:1px solid #ddd;">
${studentName}
</td>
</tr>

<tr>
<td style="padding:10px;border:1px solid #ddd;"><b>Matric</b></td>
<td style="padding:10px;border:1px solid #ddd;">
${matric}
</td>
</tr>

<tr>
<td style="padding:10px;border:1px solid #ddd;"><b>Assessment</b></td>
<td style="padding:10px;border:1px solid #ddd;">
${assessmentType}
</td>
</tr>

<tr>
<td style="padding:10px;border:1px solid #ddd;"><b>Status</b></td>
<td style="padding:10px;border:1px solid #ddd;">

<span style="
background:#F57C00;
color:white;
padding:4px 12px;
border-radius:12px;
font-size:12px;
font-weight:bold;
">

Pending ${daysPending} Day(s)

</span>

</td>
</tr>

</table>

<div style="
background:#FFF8E1;
border-left:5px solid #F57C00;
padding:18px;
margin:30px 0;
border-radius:6px;
">

<strong style="color:#E65100;">
Reminder
</strong>

<p style="margin:10px 0 0 0;line-height:1.6;">

This CQI case has remained pending for
<strong>${daysPending} day(s)</strong>.

Please complete and document the intervention in PPBMS as soon as possible.

The student has <strong>not</strong> been copied in this email.

</p>

</div>

<div style="text-align:center;margin:35px;">

<a href="https://ppbms.my/"
style="
background:#53257f;
color:white;
padding:16px 40px;
text-decoration:none;
border-radius:8px;
font-weight:bold;
font-size:16px;
display:inline-block;
box-shadow:0 2px 6px rgba(0,0,0,.15);
">

Review & Record CQI Intervention

</a>

</div>

<h3 style="color:#53257f;">
Action Required
</h3>

<ul style="line-height:1.8;padding-left:20px;">

<li>Review the outstanding CQI case.</li>

<li>Record the appropriate <strong>Continuous Quality Improvement (CQI)</strong> intervention and follow-up action in PPBMS.</li>

<li>Complete and document the intervention as soon as possible.</li>

<li>This notification has been sent <strong>only to the registered supervisor</strong>. The student has <strong>not</strong> been copied in this email.</li>

</ul>

<p style="
margin-top:25px;
line-height:1.7;
color:#444;
">

Thank you for your prompt attention and continued commitment to maintaining the quality of postgraduate education and assessment.

</p>

<hr style="
margin:40px 0;
border:none;
border-top:1px solid #ddd;
">

<div style="
background:#F7F7F7;
padding:20px;
border-radius:8px;
">

<h3 style="
margin-top:0;
color:#53257f;
">
PPBMS Administrator
</h3>

<p style="
margin:0;
line-height:1.8;
">

<strong>
Assoc. Prof. Dr. Hazwani Ahmad Yusof @ Hanafi
</strong><br>

Deputy Director (Academic & International)<br>

Pusat Kanser Tun Abdullah Ahmad Badawi (PKTAAB)<br>

Universiti Sains Malaysia

</p>

<p style="margin-top:15px;">

📧
<a href="mailto:hazwanihanafi@usm.my"
style="
color:#53257f;
text-decoration:none;
font-weight:bold;
">

hazwanihanafi@usm.my

</a>

</p>

</div>

<p style="
font-size:12px;
color:#777;
text-align:center;
line-height:1.7;
margin-top:30px;
">

This notification was automatically generated by the
<strong>Postgraduate Progress Based Monitoring System (PPBMS)</strong>,
developed by
<strong>Pusat Kanser Tun Abdullah Ahmad Badawi (PKTAAB),
Universiti Sains Malaysia</strong>,
to support postgraduate progress monitoring,
Continuous Quality Improvement (CQI),
and institutional quality assurance.

<br><br>

Please do not reply directly to this email.
For enquiries or technical assistance, please contact the PPBMS Administrator.

</p>

</td>
</tr>

</table>

</td>
</tr>

</table>

</body>
</html>
`;

  const toEmail = TEST_MODE ? TEST_EMAIL : supervisorEmail;

  await sendEmail({
    to: toEmail,
    subject: TEST_MODE
      ? `[PPBMS TEST] CQI Reminder – ${studentName}`
      : `[PPBMS] Reminder: CQI Pending (${daysPending} Day${daysPending === 1 ? "" : "s"})`,
    text: emailText,
    html: emailHtml,
  });
}
