import sendEmail from "../services/sendEmail.js";

const TEST_MODE = process.env.EMAIL_TEST_MODE === "true";
const TEST_EMAIL = "hazwanihanafi@gmail.com";

/* =========================================================
   ⏰ DELAY ALERT → STUDENT (CC SUPERVISOR ONLY)
========================================================= */
   export async function sendDelayAlert({
  studentName,
  studentEmail,
  supervisorEmail,
  studentStatus,
  delays,
}) {

  console.log("===== INSIDE sendDelayAlert =====");
  console.log({
    studentName,
    studentStatus,
    studentEmail,
    supervisorEmail,
  });

// Only send to ACTIVE or STUDY SUSPENSION students
const status = (studentStatus || "").trim().toUpperCase();

const allowedStatuses = ["ACTIVE", "STUDY SUSPENSION"];

if (!allowedStatuses.includes(status)) {
  console.log(
    `⏭️ Skipping email for ${studentName} (Status: ${studentStatus})`
  );
  return;
}

  // ✅ Basic validation
  if (!studentEmail || !studentEmail.includes("@")) {
    throw new Error("Invalid student email");
  }

  // Supervisor email is optional
if (supervisorEmail && !supervisorEmail.includes("@")) {
  throw new Error("Invalid supervisor email");
}

  if (!Array.isArray(delays)) {
    throw new Error("Delays must be an array");
  }

  const validDelays = delays.filter(
    d => d && d.activity && typeof d.remaining_days === "number"
  );

  if (validDelays.length === 0) {
    throw new Error("No valid delayed milestones");
  }

  const delayList = validDelays
    .map(d => `• ${d.activity} (Delayed ${Math.abs(d.remaining_days)} days)`)
    .join("\n");

  const emailText = (
`Dear ${studentName},

This is an automated notification from the Postgraduate Progress Based Monitoring System (PPBMS), a progress monitoring system developed by the Pusat Kanser Tun Abdullah Ahmad Badawi (PKTAAB), Universiti Sains Malaysia, to facilitate the monitoring of postgraduate students' research progress and milestones.

PPBMS has been introduced to postgraduate students through a series of briefing and training workshops. Students are expected to keep their research progress records accurate and up to date throughout their candidature.

Based on the current records in PPBMS, the following research milestone(s) are overdue:

${delayList}

Action Required

• Please log in to PPBMS using your USM email address and password.

PPBMS Login:
https://ppbms.my/

If you have not previously activated your PPBMS account, please click "Set Password" on the login page to create your password before logging in.
  
• If you have already completed any of the milestones listed above, please mark the milestone as "Completed" in PPBMS.
• Please upload the link of the relevant supporting documents for each completed milestone. These documents serve as official evidence for postgraduate progress monitoring, programme quality assurance, and institutional audit purposes.
• If you believe the information displayed is inaccurate or require assistance, please consult your supervisor or contact the PPBMS Administrator.

PPBMS Administrator
Assoc. Prof. Dr. Hazwani Ahmad Yusof @ Hanafi
Deputy Director (Academic & International)
Pusat Kanser Tun Abdullah Ahmad Badawi (PKTAAB)
Universiti Sains Malaysia
Email: hazwanihanafi@usm.my

This notification has been copied to your supervisor for information and progress monitoring.

Thank you for your prompt attention and cooperation in ensuring that your postgraduate research records in PPBMS remain accurate, complete, and up to date.

Kind regards,

PPBMS Notification System
Postgraduate Progress Based Monitoring System (PPBMS)
Pusat Kanser Tun Abdullah Ahmad Badawi (PKTAAB)
Universiti Sains Malaysia

This is an automated email generated by PPBMS. Please do not reply directly to this email.`
).trim();

      const emailHtml = `
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
</head>

<body style="
font-family:Arial,sans-serif;
background:#f5f5f5;
padding:30px;
">

<div style="
max-width:700px;
margin:auto;
background:#ffffff;
padding:35px;
border-radius:8px;
">

<h2 style="color:#53257f;">
PPBMS Milestone Delay Alert
</h2>

<p>Dear <strong>${studentName}</strong>,</p>

<p>
This is an automated notification from the
<strong>Postgraduate Progress Based Monitoring System (PPBMS)</strong>.
</p>

<p>
The following milestone(s) are overdue:
</p>

<ul>
${validDelays.map(d =>
`<li>${d.activity} (Delayed ${Math.abs(d.remaining_days)} days)</li>`
).join("")}
</ul>

<p>
Please log in to PPBMS using your USM email address.
</p>

<p style="text-align:center;margin:30px 0;">

<a href="https://ppbms.my/"
style="
background:#53257f;
color:#ffffff;
padding:14px 28px;
text-decoration:none;
border-radius:6px;
font-weight:bold;
display:inline-block;
">
Login to PPBMS
</a>

</p>

<p>
If this is your first login, please click
<strong>Set Password</strong> on the login page.
</p>

<hr>

<p>
<strong>PPBMS Administrator</strong><br>
Assoc. Prof. Dr. Hazwani Ahmad Yusof @ Hanafi<br>
Deputy Director (Academic & International)<br>
Pusat Kanser Tun Abdullah Ahmad Badawi (PKTAAB)<br>
Universiti Sains Malaysia<br>
<a href="mailto:hazwanihanafi@usm.my">
hazwanihanafi@usm.my
</a>
</p>

<p style="font-size:12px;color:#777;">
This is an automated email generated by PPBMS.
Please do not reply directly to this email.
</p>

</div>

</body>
</html>
`;
   
  // 🔒 TEST MODE GUARD
  const toEmail = TEST_MODE ? TEST_EMAIL : studentEmail;
  const ccEmail = TEST_MODE ? undefined : supervisorEmail;

  console.log("📧 Sending delay alert:", {
    to: toEmail,
    cc: ccEmail,
    testMode: TEST_MODE,
    milestones: validDelays.map(d => d.activity),
  });

  await sendEmail({
  to: toEmail,
  cc: ccEmail,
  subject: TEST_MODE
    ? `[PPBMS TEST] Milestone Delay Alert – ${studentName}`
    : `[PPBMS] Milestone Delay Alert – ${studentName}`,
  text: emailText,      // Fallback for clients that don't support HTML
  html: emailHtml,      // HTML version
});
      
}
/* =========================================================
   📊 CQI ALERT → SUPERVISOR (STUDENT NOT COPIED)
========================================================= */
export async function sendCQIAlert({
  supervisorEmail,
  studentName,
  matric,
  studentStatus,
  assessmentType,
  cqiIssues,
}) {

   // Only send CQI notifications for ACTIVE or STUDY SUSPENSION students
const status = (studentStatus || "").trim().toUpperCase();

const allowedStatuses = ["ACTIVE", "STUDY SUSPENSION"];

if (!allowedStatuses.includes(status)) {
  console.log(
    `⏭️ Skipping CQI alert for ${studentName} (Status: ${studentStatus})`
  );
  return;
}
  // 🔍 DEBUG LOGS (CRITICAL — MUST BE BEFORE VALIDATION)
  console.log("📧 CQI supervisorEmail =", supervisorEmail);
  console.log("📧 CQI payload =", {
    supervisorEmail,
    studentName,
    matric,
    assessmentType,
    cqiIssues,
  });

  if (!supervisorEmail || !supervisorEmail.includes("@")) {
    throw new Error("Invalid supervisor email");
  }

  if (!Array.isArray(cqiIssues) || cqiIssues.length === 0) {
    throw new Error("Invalid CQI issues");
  }

  const issuesText = cqiIssues
    .map(i => `• ${i.plo}: ${i.reason}`)
    .join("\n");

  const emailText = (
    `Dear Supervisor,

Continuous Quality Improvement (CQI) has been automatically detected.

Student    : ${studentName}
Matric     : ${matric}
Assessment : ${assessmentType}

Affected PLO(s):
${issuesText}

(Student is NOT copied.)

Please log in to PPBMS and record intervention within 30 days.

— PPBMS System`
  ).trim();

  const toEmail = TEST_MODE ? TEST_EMAIL : supervisorEmail;

  await sendEmail({
    to: toEmail,
    subject: TEST_MODE
      ? `[PPBMS TEST] CQI Detected – ${studentName}`
      : `[PPBMS] CQI Detected – ${studentName} (${assessmentType})`,
    text: emailText,
  });
}

/* =========================================================
   🔔 CQI REMINDER → SUPERVISOR
========================================================= */
export async function sendCQIReminder({
  supervisorEmail,
  studentName,
  matric,
  studentStatus,
  assessmentType,
  daysPending,
}) {
   // Only send CQI reminders for ACTIVE or STUDY SUSPENSION students
const status = (studentStatus || "").trim().toUpperCase();

const allowedStatuses = ["ACTIVE", "STUDY SUSPENSION"];

if (!allowedStatuses.includes(status)) {
  console.log(
    `⏭️ Skipping CQI reminder for ${studentName} (Status: ${studentStatus})`
  );
  return;
}
  if (!supervisorEmail || !supervisorEmail.includes("@")) {
    throw new Error("Invalid supervisor email");
  }

  const emailText = (
    `Dear Supervisor,

This is a reminder that a CQI case remains pending.

Student    : ${studentName}
Matric     : ${matric}
Assessment : ${assessmentType}
Days pending : ${daysPending} days

(Student is NOT copied.)

— PPBMS System`
  ).trim();

  const toEmail = TEST_MODE ? TEST_EMAIL : supervisorEmail;

  await sendEmail({
    to: toEmail,
    subject: TEST_MODE
      ? `[PPBMS TEST] CQI Reminder – ${studentName}`
      : `[PPBMS] REMINDER: CQI Pending > ${daysPending} Days`,
    text: emailText,
  });
}

