import express from "express";
import jwt from "jsonwebtoken";
import { readMasterTracking, readOrientationProgress, upsertOrientationProgress, updateOrientationFinal } from "../services/googleSheets.js";

const router = express.Router();
function auth(req,res,next){
  const token=(req.headers.authorization||"").replace("Bearer ","");
  if(!token) return res.status(401).json({error:"No token"});
  try { req.user=jwt.verify(token,process.env.JWT_SECRET); next(); }
  catch { return res.status(401).json({error:"Invalid token"}); }
}
const asBool=v=["true","1","yes"].includes(String(v).toLowerCase());
function rowToProgress(r){return {moduleId:Number(r.module_id),contentRead:asBool(r.content_read),videoCompleted:asBool(r.video_completed),videoPercent:Number(r.video_percent||0),activityCompleted:asBool(r.activity_completed),quizCompleted:asBool(r.quiz_completed),quizScore:Number(r.quiz_score||0),acknowledged:asBool(r.acknowledged),completed:asBool(r.completed),completedAt:r.completed_at||null,finalScore:Number(r.final_score||0),finalPassed:asBool(r.final_passed),declarationAt:r.declaration_at||null};}
async function getStudent(req){const email=String(req.user.email||"").toLowerCase(); const rows=await readMasterTracking(process.env.SHEET_ID); const raw=rows.find(r=>String(r["Student's Email"]||"").toLowerCase()===email); if(!raw) throw new Error("Student record not found in Master Tracking"); return {email,matric:String(raw["Matric"]||"")};}
router.get("/progress",auth,async(req,res)=>{try{const s=await getStudent(req); const rows=await readOrientationProgress(process.env.SHEET_ID); const own=rows.filter(r=>String(r.email||"").toLowerCase()===s.email); const progress={}; own.forEach(r=>{progress[Number(r.module_id)]=rowToProgress(r);}); res.json({progress});}catch(e){res.status(500).json({error:e.message});}});
router.post("/module/:id",auth,async(req,res)=>{try{const s=await getStudent(req); const id=Number(req.params.id); const rows=await readOrientationProgress(process.env.SHEET_ID); const existing=rows.find(r=>String(r.email||"").toLowerCase()===s.email&&String(r.module_id)===String(id)); const current=existing?rowToProgress(existing):{}; const body=req.body||{}; const next={...current}; ["contentRead","videoCompleted","activityCompleted","quizCompleted","acknowledge"].forEach(k=>{if(body[k]!==undefined) next[k]=!!body[k];}); if(body.videoPercent!==undefined) next.videoPercent=Number(body.videoPercent)||0; if(body.quizScore!==undefined) next.quizScore=Number(body.quizScore)||0; next.completed=!!(next.contentRead&&next.activityCompleted&&next.quizCompleted&&next.quizScore>=70&&next.acknowledged); if(next.completed&&!current.completed) next.completedAt=new Date().toISOString(); const patch={content_read:next.contentRead?"TRUE":"FALSE",video_completed:next.videoCompleted?"TRUE":"FALSE",video_percent:next.videoPercent,activity_completed:next.activityCompleted?"TRUE":"FALSE",quiz_completed:next.quizCompleted?"TRUE":"FALSE",quiz_score:next.quizScore,acknowledged:next.acknowledged?"TRUE":"FALSE",completed:next.completed?"TRUE":"FALSE",completed_at:next.completedAt||""}; await upsertOrientationProgress({sheetId:process.env.SHEET_ID,email:s.email,matric:s.matric,moduleId:id,patch}); const latest=await readOrientationProgress(process.env.SHEET_ID); const progress={}; latest.filter(r=>String(r.email||"").toLowerCase()===s.email).forEach(r=>{progress[Number(r.module_id)]=rowToProgress(r);}); res.json({progress});}catch(e){console.error(e);res.status(500).json({error:e.message});}});
router.post("/final-assessment",auth,async(req,res)=>{try{const s=await getStudent(req); const score=Math.max(0,Math.min(100,Number(req.body?.score)||0)); await updateOrientationFinal({sheetId:process.env.SHEET_ID,email:s.email,matric:s.matric,finalScore:score}); res.json({score,passed:score>=70,message:score>=70?"Passed. You may proceed to the declaration step.":"Not passed yet. Review the modules and try again."});}catch(e){res.status(500).json({error:e.message});}});
router.post("/declaration",auth,async(req,res)=>{try{const s=await getStudent(req); const score=Number(req.body?.score||0); if(score<70) return res.status(400).json({error:"Final assessment pass mark is 70%."}); await updateOrientationFinal({sheetId:process.env.SHEET_ID,email:s.email,matric:s.matric,finalScore:score,declaration:true}); res.json({success:true});}catch(e){res.status(500).json({error:e.message});}});
export default router;
